---
title: "Exploratory Analysis"
output: html_document
---

## osu! RME Tournament Rating System

### Authors

Anh-Minh Nguyen (anhngu@uw.edu)

### Date

Spring 2024

### Abstract

Players of the online rhythm game osu! often question if the official ranking system accurately rates player skill. To explore this, we calculate a Rhythm Metrics Elo (RME) for every active tournament participant in osu! in the year 2023. We then analyze differences between the hierarchy of players in RME rating versus the official rankings. 

### Keywords

Keywords: e-sports; ranking systems; glicko-2; skill-based rating

### Introduction  

osu! is a rhythm game with about a million active users and a fairly large tournament community. In osu!, a player plays a "map", a set of notes composed to the beat of a song. Upon completing the map, the player receives a numeric "score" that represents how well they played the map. 

There is an official osu! performance rating system used to rank the skill level of all players. However, as many players notice, the official rating system does not encompass every skill that someone can master in osu!. Tournament play highlights these niche skillsets, offering more varied types of maps to test players on. Most of the best tournament players are indeed in the highest official ranks and vice versa, but some players stand out as especially skilled at either tournament play or singleplayer play.

Some questions I want to answer are:
- Who are the best tournament players?
- Are highly ranked players on the official leaderboards similarly highly ranked in tournament performance?
- Are highly performant players in tournaments similarly highly ranked in the official leaderboards?
- Is the official osu! ranking system representative of overall skill?

### Related Work  

In this project I will compare scores set by players, but I will also simplify the analysis by only considering "wins", "draws", and "losses", defined as achieving a higher, equal, or lower score as another player in the same match.

This simplification allows me to use ranking systems like Elo, used for zero-sum games like chess, tennis, and other e-sports (Ebtekar) (Moncav). In particular, I want to use the Glicko-2 rating system, which incorporates "rating deviation" that specifies how confident the rating system is in the player's true rating (Glickman).  

Ebtekar, A., & Liu, P. (2021). Elo-MMR: A rating system for massive multiplayer competitions. Proceedings of the Web Conference 2021. https://doi.org/10.1145/3442381.3450091 

Glickman, M. E. (2022, March 22). Example of the glicko-2 system. http://www.glicko.net/glicko/glicko2.pdf 

Moncav, M. (2020, March 6). What is elo? an explanation for competitive gaming’s Hidden Rating System. Dot Esports. https://dotesports.com/general/news/elo-ratings-explained-20565 

### The Dataset

Where did you find the data? Please include a link to the data source
Who collected the data?  

I gathered my data by querying the osu! API ([link to documentation](https://osu.ppy.sh/docs/index.html)).

How was the data collected or generated?  

To collect data on player scores, I first approximated the first and last tournament matches held in 2023. I found match IDs [105988619](https://osu.ppy.sh/community/matches/105988619) and [111977659](https://osu.ppy.sh/community/matches/111977659). Then, I queried the osu! API for every match ID in this range, added 20,000 IDs on either side, and filtered out various undesired data (see Limitations and Challenges). I then wrote each score to a .csv file. 

Why was the data collected?  

I collected this data for use in this project.

Explaining the datasets

There are two tables of data. The first, **Scores**, records all scores set in tournament matches in the year 2023. The second, **Players**, records information about each player who appears in **Scores**, including their official rank, calculated RME rating, and country. 

Data collection is about 60% complete. Currently, there are about 1,140,000 observations in the **Scores** dataset, and about 17,000 observations in the **Players** dataset. These encompass every osu! tourney match played from Jan 1, 2023 to August 14, 2023

There are 8 features in the Scores dataset:
- Match ID - the ID number of the tournament match (integer)
- Tourney Abbreviation - a string representing the tourney this match was part of
- Datetime - when the map was played (expressed in UTC)
- Map ID - what map was played (integer)
- Player ID - who played this map (integer)
- Username - who played this map (string), accessed during data collection
- Mods - what ingame modifications the player had active during the map (enum)
- Score - what score the player achieved (integer from 0 to 1,250,000)

There are 6 features in the Players dataset:
- Player ID - a player's ID 
- Username - this player's username
- Global rank - this player's official rank (integer)
- Performance points - this player's official performance score (float)
- RME Rating - this player's RME rating (float)
- Location - the country displayed on this player's profile (enum: ISO 3166-1 alpha-2 code)

Note that username, global rank, performance points, and location were accessed on May 18th, 04:00 UTC.

What, if any, ethical questions or questions of power do you need to consider when working with this data?  
What are possible limitations or problems with this data?   (at least 200 words)

One limitation of this data is that I only processed tournament matches that happened in 2023. A more extensive rating system would tally matches across several years, but I will only query the osu! API for one year's worth of matches. A related limitation is that I accessed player data 5 months into 2024. Players will have gained or lost ranks in the 5 months since 2023, which will limit the conclusions I can make.

A problem that I mostly addressed is the fact that not all maps played in a tournament match are actually part of the match. Players will often play a "warm-up" map before the match, which is logged in the match history. Players can also play maps after the match is over, which is also logged in the match history. I cleaned most occurences of these by analyzing the amount of players who played each map.

Finally, I improperly used multiprocessing in my API scraper program, so a few dozen rows in my Scores dataset were overwritten by fellow scraper processes. I also forgot to filter out any non-osu!standard games. In the next phase of the project, I will requery every match ID after fixing these problems. For now, I have omitted these rows in my analysis.

### Implications

Finding discrepancies between players' global ranks and tournament performance could inform the development team at osu! about what skillsets may be undervalued in the official rating system.

### Limitations & Challenges

A fundamental limitation of applying an Elo model to osu! is that, in team-based tournaments, a player is free to not play a map, so if they don't want to play a map, they can have their teammates fill in. This means that a player can always play to their strengths. A hypothetical player who always plays well on a single type of map and never plays any other map could theoretically top the rankings, despite most of the commonly accepted "best tournament players" having well-rounded skillsets.

Data cleaning and preparation were the bulk of the work in this project. I filtered out these conditions while building my dataset:
- Matches that weren't tournament matches
- Some maps which were not part of a match, e.g. warm-ups, tiebreaker showcases
- Matches which had zero maps played
- Maps which have been deleted from the osu! server
- Maps not played in the osu! standard gamemode

When calculating player ratings, I also filtered out these conditions:
- Maps played by only a single player
- Duplicated rows
- Malformed rows


I'm not sure if I can perfectly detect all eligible maps played in all tournament matches. I'll also need to consider any adjustments to the Glicko-2 rating system when parsing my player data. Glicko-2 ratings are only defined for a set of players who could all play each other, but many osu! players will only play in rank-restricted tournaments, where they only play against other players of a similar official rank (for example, players from global rank 10,000 to rank 50,000).

### Summary Information

Write a summary paragraph of findings that includes the 5 values calculated from your summary information R script

### Table

Include a table of aggregate information

Describe why you included the table and what information it reveals

### Chart 1

Include a chart

Describe why you chose this chart and what information it reveals

Here's an example of how to run an R script inside an RMarkdown file:

``````{r, echo = FALSE, code = readLines("chart1_example.R")}
```

### Chart 2

Include a chart

Describe why you chose this chart and what information it reveals

### Chart 3

Include a chart

Describe why you chose this chart and what information it reveals
